apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: data-lake
spec:
  version: 8.8.1
  nodeSets:
  - name: default
    count: 2
    config:
      node.store.allow_mmap: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          env:
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx512m
          resources:
            requests:
              memory: 512Mi
              cpu: 0.5
            limits:
              memory: 2Gi
              cpu: 2
