---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ralph-env-cm
data:

  # LRS backend configuration

  ## Elasticsearch LRS backend
  RALPH_BACKENDS__LRS__ES__DEFAULT_INDEX: "statements"
  RALPH_BACKENDS__LRS__ES__ALLOW_YELLOW_STATUS: "False"
  RALPH_BACKENDS__LRS__ES__CLIENT_OPTIONS__ca_certs: "/usr/local/share/ca-certificates/ca.crt"
  RALPH_BACKENDS__LRS__ES__CLIENT_OPTIONS__verify_certs: "True"
  RALPH_BACKENDS__LRS__ES__LOCALE_ENCODING: "utf8"
  RALPH_BACKENDS__LRS__ES__POINT_IN_TIME_KEEP_ALIVE: "1m"
  RALPH_BACKENDS__LRS__ES__READ_CHUNK_SIZE: "500"
  RALPH_BACKENDS__LRS__ES__REFRESH_AFTER_WRITE: "False"
  RALPH_BACKENDS__LRS__ES__WRITE_CHUNK_SIZE: "500"

  ## Mongo LRS backend
  # RALPH_BACKENDS__LRS__MONGO__DEFAULT_COLLECTION: "foo"
  # RALPH_BACKENDS__LRS__MONGO__DEFAULT_DATABASE: "statements"
  # RALPH_BACKENDS__LRS__MONGO__CLIENT_OPTIONS__document_class: ""
  # RALPH_BACKENDS__LRS__MONGO__CLIENT_OPTIONS__tz_aware: "False"
  # RALPH_BACKENDS__LRS__MONGO__LOCALE_ENCODING: "utf8"
  # RALPH_BACKENDS__LRS__MONGO__READ_CHUNK_SIZE: "500"
  # RALPH_BACKENDS__LRS__MONGO__WRITE_CHUNK_SIZE: "500"

  ## ClickHouse LRS backend
  # RALPH_BACKENDS__LRS__CLICKHOUSE__HOST: "clickhouse"
  # RALPH_BACKENDS__LRS__CLICKHOUSE__PORT: "8123"
  # RALPH_BACKENDS__LRS__CLICKHOUSE__DATABASE: "xapi"
  # RALPH_BACKENDS__LRS__CLICKHOUSE__EVENT_TABLE_NAME: "xapi_events_all"
  # RALPH_BACKENDS__LRS__CLICKHOUSE__CLIENT_OPTIONS__date_time_input_format: ""
  # RALPH_BACKENDS__LRS__CLICKHOUSE__LOCALE_ENCODING: "utf8"
  # RALPH_BACKENDS__LRS__CLICKHOUSE__READ_CHUNK_SIZE: "500"
  # RALPH_BACKENDS__LRS__CLICKHOUSE__WRITE_CHUNK_SIZE: "500"
  # RALPH_BACKENDS__LRS__CLICKHOUSE__IDS_CHUNK_SIZE: "8123"

  # CLI configuration

  ## LDP data backend
  # RALPH_BACKENDS__DATA__LDP__CONSUMER_KEY: ""
  # RALPH_BACKENDS__DATA__LDP__DEFAULT_STREAM_ID: ""
  # RALPH_BACKENDS__DATA__LDP__ENDPOINT: ""
  # RALPH_BACKENDS__DATA__LDP__REQUEST_TIMEOUT: ""
  # RALPH_BACKENDS__DATA__LDP__SERVICE_NAME: ""

  ## Swift data backend
  # RALPH_BACKENDS__DATA__SWIFT__IDENTITY_API_VERSION: "3"
  # RALPH_BACKENDS__DATA__SWIFT__TENANT_ID: "cd238e84310a46e58af7f1d515887d88"
  # RALPH_BACKENDS__DATA__SWIFT__TENANT_NAME: "RegionOne"
  # RALPH_BACKENDS__DATA__SWIFT__PROJECT_DOMAIN_NAME: "Default"
  # RALPH_BACKENDS__DATA__SWIFT__REGION_NAME: "RegionOne"
  # RALPH_BACKENDS__DATA__SWIFT__OBJECT_STORAGE_URL: "http://swift:8080/v1/KEY_cd238e84310a46e58af7f1d515887d88/test_container"
  # RALPH_BACKENDS__DATA__SWIFT__USER_DOMAIN_NAME: "Default"
  # RALPH_BACKENDS__DATA__SWIFT__DEFAULT_CONTAINER: ""
  # RALPH_BACKENDS__DATA__SWIFT__LOCALE_ENCODING: "Default"

  ## S3 data backend
  # RALPH_BACKENDS__DATA__S3__ENDPOINT_URL: ""
  # RALPH_BACKENDS__DATA__S3__DEFAULT_REGION: ""
  # RALPH_BACKENDS__DATA__S3__DEFAULT_BUCKET_NAME: ""
  # RALPH_BACKENDS__DATA__S3__LOCALE_ENCODING: ""
  # RALPH_BACKENDS__DATA__S3__READ_CHUNK_SIZE: ""
  # RALPH_BACKENDS__DATA__S3__WRITE_CHUNK_SIZE: ""

  ## Elasticsearch data backend
  # RALPH_BACKENDS__DATA__ES__DEFAULT_INDEX: "statements"
  # RALPH_BACKENDS__DATA__ES__ALLOW_YELLOW_STATUS: "False"
  # RALPH_BACKENDS__DATA__ES__CLIENT_OPTIONS__ca_certs: "False"
  # RALPH_BACKENDS__DATA__ES__CLIENT_OPTIONS__verify_certs: "False"
  # RALPH_BACKENDS__DATA__ES__LOCALE_ENCODING: "utf8"
  # RALPH_BACKENDS__DATA__ES__POINT_IN_TIME_KEEP_ALIVE: "1m"
  # RALPH_BACKENDS__DATA__ES__READ_CHUNK_SIZE: "500"
  # RALPH_BACKENDS__DATA__ES__REFRESH_AFTER_WRITE: "False"
  # RALPH_BACKENDS__DATA__ES__WRITE_CHUNK_SIZE: "500"

  ## Mongo data backend
  # RALPH_BACKENDS__DATA__MONGO__DEFAULT_COLLECTION: "foo"
  # RALPH_BACKENDS__DATA__MONGO__DEFAULT_DATABASE: "statements"
  # RALPH_BACKENDS__DATA__MONGO__CLIENT_OPTIONS__document_class: ""
  # RALPH_BACKENDS__DATA__MONGO__CLIENT_OPTIONS__tz_aware: "False"
  # RALPH_BACKENDS__DATA__MONGO__LOCALE_ENCODING: "utf8"
  # RALPH_BACKENDS__DATA__MONGO__READ_CHUNK_SIZE: "500"
  # RALPH_BACKENDS__DATA__MONGO__WRITE_CHUNK_SIZE: "500"

  ## ClickHouse data backend
  # RALPH_BACKENDS__DATA__CLICKHOUSE__HOST: "clickhouse"
  # RALPH_BACKENDS__DATA__CLICKHOUSE__PORT: "8123"
  # RALPH_BACKENDS__DATA__CLICKHOUSE__DATABASE: "xapi"
  # RALPH_BACKENDS__DATA__CLICKHOUSE__EVENT_TABLE_NAME: "xapi_events_all"
  # RALPH_BACKENDS__DATA__CLICKHOUSE__CLIENT_OPTIONS__date_time_input_format: ""
  # RALPH_BACKENDS__DATA__CLICKHOUSE__LOCALE_ENCODING: "utf8"
  # RALPH_BACKENDS__DATA__CLICKHOUSE__READ_CHUNK_SIZE: "500"
  # RALPH_BACKENDS__DATA__CLICKHOUSE__WRITE_CHUNK_SIZE: "500"

  ## LRS HTTP backend
  # RALPH_BACKENDS__DATA__LRS__HEADERS__X_EXPERIENCE_API_VERSION: "1.0.3"
  # RALPH_BACKENDS__DATA__LRS__HEADERS__CONTENT_TYPE: "application/json"
  # RALPH_BACKENDS__DATA__LRS__STATUS_ENDPOINT: "/__heartbeat__"
  # RALPH_BACKENDS__DATA__LRS__STATEMENTS_ENDPOINT: "/xAPI/statements"
---
