---
apiVersion: v1
kind: Secret
metadata:
  name: ralph-env-secret
type: Opaque
stringData:

  # LRS backend configuration

  ## Elasticsearch LRS backend
  RALPH_BACKENDS__LRS__ES__HOSTS: "https://elastic:<PASSWORD>@data-lake-es-http:9200"

  ## Mongo LRS backend
  # RALPH_BACKENDS__LRS__MONGO__CONNECTION_URI: "mongodb://mongo:27017/"

  ## ClickHouse LRS backend
  # RALPH_BACKENDS__LRS__CLICKHOUSE__USERNAME: ""
  # RALPH_BACKENDS__LRS__CLICKHOUSE__PASSWORD: ""

  # CLI configuration

  ## LDP data backend
  # RALPH_BACKENDS__DATA__LDP__APPLICATION_KEY: ""
  # RALPH_BACKENDS__DATA__LDP__APPLICATION_SECRET: ""

  ## Swift data backend
  # RALPH_BACKENDS__DATA__SWIFT__AUTH_URL: "http://swift:35357/v3/"
  # RALPH_BACKENDS__DATA__SWIFT__USERNAME: "demo"
  # RALPH_BACKENDS__DATA__SWIFT__PASSWORD: "demo"

  ## S3 data backend
  # RALPH_BACKENDS__DATA__S3__ACCESS_KEY_ID: ""
  # RALPH_BACKENDS__DATA__S3__SECRET_ACCESS_KEY: ""
  # RALPH_BACKENDS__DATA__S3__SESSION_TOKEN: ""

  ## Elasticsearch data backend
  # RALPH_BACKENDS__DATA__ES__HOSTS: "http://elasticsearch:9200"

  ## Mongo data backend
  # RALPH_BACKENDS__DATA__MONGO__CONNECTION_URI: "mongodb://mongo:27017/"

  ## ClickHouse data backend
  # RALPH_BACKENDS__DATA__CLICKHOUSE__USERNAME: ""
  # RALPH_BACKENDS__DATA__CLICKHOUSE__PASSWORD: ""

  ## LRS HTTP backend
  # RALPH_BACKENDS__DATA__LRS__BASE_URL: "http://ralph:secret@0.0.0.0:8100/"
  # RALPH_BACKENDS__DATA__LRS__USERNAME: "ralph"
  # RALPH_BACKENDS__DATA__LRS__PASSWORD: "secret"
---
