services:
  ralph:
    image: fundocker/ralph:5.0.1
    env_file:
      - env.d/ralph.env
    ports:
      - "8080:8080"
    command:
      - "uvicorn"
      - "ralph.api:app"
      - "--proxy-headers"
      - "--log-config"
      - "logging_config.yaml"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8080"
    configs:
      - source: logging_config
        target: /app/logging_config.yaml
    volumes:
      - ./auth/:/var/run/ralph/
    healthcheck:
      test: curl -f http://localhost:8080/__heartbeat__ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      replicas: 3
      restart_policy:
        condition: any
    networks:
      - backend

configs:
  logging_config:
    external: true

networks:
  backend:
    external: true
