apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.loggingConfigConfigMap }}"
  labels:
    {{- include "ralph.labels" . | nindent 4 }}
data:
  {{ with .Values.loggingConfig }}
  logging-config.yaml: |
    {{- toYaml . | nindent 4 }}
  {{- end }}
