{{- if .Values.ralph_cronjobs }}
{{- range $job := .Values.ralph_cronjobs }}
{{- with $ -}}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ template "ralph.fullname" . }}-{{ $job.name }}"
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "ralph.labels" . | nindent 4 }}
    type: job
spec:
  schedule: {{ $job.schedule | quote }}
  successfulJobsHistoryLimit: 2
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  suspend: false
  jobTemplate:
    spec:
      template:
        metadata:
          name: "{{ template "ralph.fullname" . }}-{{ $job.name }}"
          labels:
            {{- include "ralph.labels" . | nindent 12 }}
            type: job
        spec:
          restartPolicy: Never
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          containers:
            - name: "{{ template "ralph.fullname" . }}-{{ $job.name }}"
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
                - bash
                - "-c"
              {{- with $job.command }}
                {{ toYaml . | nindent 16 }}
              {{- end }}
              env:
                - name: RALPH_APP_DIR
                  value: "/app/.ralph"
                - name: RALPH_AUTH_FILE
                  value: "/var/run/ralph/auth.json"
                - name: RALPH_EXECUTION_ENVIRONMENT
                  value: "{{ .Values.executionEnvironment }}"
                - name: RALPH_SENTRY_IGNORE_HEALTH_CHECKS
                  value: "{{ .Values.sentryIgnoreHealthChecks }}"
                {{- if and .Values.elastic.enabled .Values.elastic.mountCACert }}
                - name: RALPH_BACKENDS__DATA__ES__CLIENT_OPTIONS__ca_certs
                  value: "/usr/local/share/ca-certificates/ca.crt"
                {{- end }}
              envFrom:
                - secretRef:
                    name: {{ tpl .Values.envFromSecret . | quote }}
              volumeMounts:
                - name: {{ .Values.volumes.history.name }}
                  mountPath: /app/.ralph
                {{- if .Values.elastic.mountCASecret }}
                - name: es-ca-certificate
                  mountPath: /usr/local/share/ca-certificates/
                {{- end }}
          volumes:
            - name: {{ .Values.volumes.history.name }}
            {{- if .Values.volumes.history.enabled }}
              persistentVolumeClaim:
                claimName: {{ .Values.volumes.history.claimName }}
            {{- else }}
              emptyDir: {}
            {{- end }}
            {{- if .Values.elastic.mountCACert }}
            - name: es-ca-certificate
              secret:
                secretName: {{ .Values.elastic.caSecretName }}
            {{- end }}
{{- end }}
{{- end }}
{{- end }}
