{{- if .Values.cronjobs }}
{{- range $job := .Values.cronjobs }}
{{- with $ -}}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ template "ralph.fullname" . }}-{{ $job.name }}"
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "ralph.labels" . | nindent 4 }}
    type: job
spec:
  schedule: {{ $job.schedule | quote }}
  successfulJobsHistoryLimit: 2
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  suspend: {{ $job.suspend }}
  jobTemplate:
    spec:
      template:
        metadata:
          name: "{{ template "ralph.fullname" . }}-{{ $job.name }}"
          labels:
            {{- include "ralph.labels" . | nindent 12 }}
            {{- with .Values.podLabels }}
            {{- toYaml . | nindent 8 }}
            {{- end }}
            type: job
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
            - name: "{{ template "ralph.fullname" . }}-{{ $job.name }}"
              securityContext: 
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              envFrom:
                - configMapRef:
                    name: {{ .Values.lrsConfigMap | quote }}
                - configMapRef:
                    name: {{ .Values.lrsEnvConfigMap | quote }}
                - secretRef:
                    name: {{ .Values.lrsEnvSecret | quote }}
              command:
                - bash
                - "-c"
                {{- with $job.command }}
                {{ toYaml . | nindent 16 }}
                {{- end }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              volumeMounts:
                - name: lrs-auth
                  mountPath: /var/run/ralph/
              {{- if and .Values.database.tls.enabled .Values.database.tls.certificatesSecret }}
                - name: db-certificates
                  mountPath: {{ .Values.database.tls.certificatesMountPath }}
              {{- end }}
              {{- if .Values.persistence.enabled }}
                - name: {{ .Values.persistence.volumes.history.name }}
                  mountPath: {{ .Values.persistence.volumes.history.mountPath }}
              {{- end }}
              {{- with .Values.extraVolumeMounts }}
                {{- toYaml . | nindent 16 }}
              {{- end }}
          restartPolicy: Never
          volumes:
            - name: lrs-auth
              secret:
                secretName: {{ .Values.lrsAuthSecret }}
          {{- if and .Values.database.tls.enabled .Values.database.tls.certificatesSecret }}
            - name: db-certificates
              secret:
                secretName: {{ .Values.database.tls.certificatesSecret }}
          {{- end }}
          {{- if .Values.persistence.enabled }}
            - name: {{ .Values.persistence.volumes.history.name }}
              persistentVolumeClaim:
          {{- if .Values.persistence.volumes.history.claimName }}
                claimName: {{ .Values.persistence.volumes.history.claimName }}
          {{- else }}
                claimName: {{ include "ralph.fullname" . }}-pvc-history
          {{- end }}
          {{- end }}
          {{- with .Values.extraVolumes }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
{{- end }}
{{- end }}
