{{- if .Values.persistence.enabled }}
{{- if not .Values.persistence.volumes.history.claimName }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ralph.fullname" . }}-pvc-history
  labels:
    {{- include "ralph.labels" . | nindent 4 }}
spec:
  accessModes:
  {{ with .Values.persistence.accessModes }}
    {{- toYaml . | indent 4 }}
  {{- end }}
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.volumes.history.size }}
{{- end }}
{{- end }}
