---
{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.envFromSecret }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ralph.labels" . | nindent 4 }}
type: Opaque
data:
    {{- if .Values.envSecrets }}
    {{- range $key, $value := .Values.envSecrets }}
    {{ $key }}: {{ $value | b64enc }}
    {{- end }}
    {{- end }}
{{- end }}
---
{{- if not .Values.lrs.authExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.lrs.authSecretName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ralph.labels" . | nindent 4 }}
type: Opaque
data:
    auth.json: {{ .Values.lrs.auth | toJson | b64enc }}
{{- end }}
