---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ralph.secret_name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ralph.labels" . | nindent 4 }}
  annotations:
    checksum/config: {{ (tpl (.Files.Glob "vault.yaml").AsSecrets . ) | sha256sum }}
type: Opaque
data:
{{- $v := $.Files.Get "vault.yaml" | fromYaml }}
{{- range $key, $val := $v }}
    {{ if contains "RALPH_" $key }}
        {{ $key | nindent 2 }}: {{ $val | b64enc }}
    {{- end }}
{{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ralph_lrs.auth_secret_name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ralph.labels" . | nindent 4 }}
  annotations:
    checksum/config: {{ (tpl (.Files.Glob "vault.yaml").AsSecrets . ) | sha256sum }}
type: Opaque
data:
{{- $v := $.Files.Get "vault.yaml" | fromYaml }}
{{ if get $v "LRS_AUTH" }}
    auth.json: {{ get $v "LRS_AUTH" | toJson | b64enc }}
{{- end }}

{{- if .Values.ralph.elastic.mount_ca_secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ralph.elastic.ca_secret_name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ralph.labels" . | nindent 4 }}
  annotations:
    checksum/config: {{ (tpl (.Files.Glob "vault.yaml").AsSecrets . ) | sha256sum }}
type: Opaque
data:
{{- $v := $.Files.Get "vault.yaml" | fromYaml }}
{{ if get $v "ES_CA_CERTIFICATE" }}
    es-cluster.pem: {{ get $v "ES_CA_CERTIFICATE" | b64enc }}
{{- end }}
{{- end }}
