---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ralph.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels: {{- include "ralph.labels" . | nindent 4 }}
spec:
  ports:
    - name: "{{ .Values.service.port }}-tcp"
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.lrs.port }}
      protocol: TCP
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePort.http)) }}
      nodePort: {{ .Values.service.nodePort.http }}
      {{- end }}
  type: {{ .Values.service.type }}
  selector: {{- include "ralph.selectorLabels" . | nindent 4 }}
