apiVersion: v1
kind: Service
metadata:
  name: {{ include "ralph.fullname" . }}
  labels:
    {{- include "ralph.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePort.http)) }}
      nodePort: {{ .Values.service.nodePort.http }}
      {{- else if eq .Values.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
  selector:
      {{- include "ralph.selectorLabels" . | nindent 4 }}
